module.exports = {
  configs: {
    recommended: {
      extends: [
        "google",
        "plugin:@angular-eslint/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:security/recommended",
        "plugin:cypress/recommended",
        "plugin:promise/recommended",
      ],
      plugins: [
        "@typescript-eslint",
        "rxjs",
        "import",
        "jsdoc",
        "prefer-arrow",
        "promise",
        "cypress",
        "prettier",
        "security",
      ],
      rules: {
        "@angular-eslint/component-selector": [
          "error",
          {
            type: "element",
            prefix: "vision",
            style: "kebab-case",
          },
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            type: "attribute",
            prefix: "vision",
            style: "camelCase",
          },
        ],
        "new-cap": "off",
        indent: ["error", 2],
        "promise/always-return": "off",
        "promise/no-return-wrap": "error",
        "promise/param-names": "error",
        "promise/catch-or-return": "error",
        "promise/no-native": "off",
        "promise/no-nesting": "warn",
        "promise/no-promise-in-callback": "warn",
        "promise/no-callback-in-promise": "warn",
        "promise/avoid-new": "warn",
        "promise/no-new-statics": "error",
        "promise/no-return-in-finally": "warn",
        "promise/valid-params": "warn",
        "object-curly-spacing": "off",
        "max-len": "off",
        "spaced-comment": "off",
        quotes: [2, "double", { avoidEscape: true }],
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            accessibility: "explicit",
          },
        ],
        "@typescript-eslint/no-empty-interface": "warn",
        "@typescript-eslint/no-floating-promises": "off",
        "@typescript-eslint/no-inferrable-types": [
          "off",
          {
            ignoreParameters: true,
          },
        ],
        "@typescript-eslint/no-unnecessary-type-assertion": "error",
        "@typescript-eslint/prefer-for-of": "warn",
        "@typescript-eslint/unified-signatures": "warn",
        "arrow-parens": ["off", "always"],
        "comma-dangle": "warn",
        eqeqeq: ["warn", "always"],
        "import/no-extraneous-dependencies": "off",
        "import/no-unassigned-import": "warn",
        "import/order": "off",
        "no-duplicate-case": "error",
        "no-duplicate-imports": "error",
        "no-empty": [
          "off",
          {
            allowEmptyCatch: true,
          },
        ],
        "no-invalid-this": "error",
        "no-redeclare": "error",
        "no-sequences": "error",
        "no-var": "warn",
        "no-void": "error",
        "prefer-const": "warn",
        "rxjs/no-async-subscribe": "error",
        "rxjs/no-create": "error",
        "rxjs/no-nested-subscribe": "error",
        "rxjs/no-subject-unsubscribe": "error",
        "rxjs/no-unsafe-subject-next": "error",
      },
    },
  }
};
